language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - composer install --dev --prefer-dist

script:
  - find ./src -type f -name '*.php' -exec php -l {} \;
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests --testdox
